import React, { useState } from 'react';
import Logo from '../logo.svg';

import Heading from '../components/Heading';
import TopSearchBar from '../components/TopSearchBar';


export default function Landing(props) {
  const weatherResponse = {
    "location": {
      "name": "New Delhi",
      "region": "Delhi",
      "country": "India",
      "lat": 28.6,
      "lon": 77.2,
      "tz_id": "Asia/Kolkata",
      "localtime_epoch": 1643691999,
      "localtime": "2022-02-01 10:36"
    },
    "current": {
      "last_updated_epoch": 1643688000,
      "last_updated": "2022-02-01 09:30",
      "temp_c": 11,
      "temp_f": 51.8,
      "is_day": 1,
      "condition": {
        "text": "Fog",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
        "code": 1135
      },
      "wind_mph": 4.3,
      "wind_kph": 6.8,
      "wind_degree": 240,
      "wind_dir": "WSW",
      "pressure_mb": 1014,
      "pressure_in": 29.94,
      "precip_mm": 0,
      "precip_in": 0,
      "humidity": 94,
      "cloud": 0,
      "feelslike_c": 10.3,
      "feelslike_f": 50.6,
      "vis_km": 0.1,
      "vis_miles": 0,
      "uv": 5,
      "gust_mph": 5.8,
      "gust_kph": 9.4,
      "air_quality": {
        "co": 8544.900390625,
        "no2": 97.30000305175781,
        "o3": 2.5999999046325684,
        "so2": 48.599998474121094,
        "pm2_5": 855.9000244140625,
        "pm10": 893.2999877929688,
        "us-epa-index": 6,
        "gb-defra-index": 10
      }
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2022-02-01",
          "date_epoch": 1643673600,
          "day": {
            "maxtemp_c": 25.1,
            "maxtemp_f": 77.2,
            "mintemp_c": 12.6,
            "mintemp_f": 54.7,
            "avgtemp_c": 18,
            "avgtemp_f": 64.4,
            "maxwind_mph": 10.7,
            "maxwind_kph": 17.3,
            "totalprecip_mm": 0,
            "totalprecip_in": 0,
            "avgvis_km": 10,
            "avgvis_miles": 6,
            "avghumidity": 46,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 0,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "uv": 5
          },
          "astro": {
            "sunrise": "07:10 AM",
            "sunset": "06:01 PM",
            "moonrise": "07:24 AM",
            "moonset": "06:09 PM",
            "moon_phase": "New Moon",
            "moon_illumination": "0"
          },
          "hour": [
            {
              "time_epoch": 1643653800,
              "time": "2022-02-01 00:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.3,
              "wind_kph": 2.2,
              "wind_degree": 21,
              "wind_dir": "NNE",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 51,
              "cloud": 2,
              "feelslike_c": 14.6,
              "feelslike_f": 58.3,
              "windchill_c": 14.6,
              "windchill_f": 58.3,
              "heatindex_c": 14.6,
              "heatindex_f": 58.3,
              "dewpoint_c": 4.5,
              "dewpoint_f": 40.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.7,
              "gust_kph": 4.3,
              "uv": 1
            },
            {
              "time_epoch": 1643657400,
              "time": "2022-02-01 01:00",
              "temp_c": 14.2,
              "temp_f": 57.6,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.6,
              "wind_kph": 2.5,
              "wind_degree": 2,
              "wind_dir": "N",
              "pressure_mb": 1013,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 52,
              "cloud": 3,
              "feelslike_c": 14.2,
              "feelslike_f": 57.6,
              "windchill_c": 14.2,
              "windchill_f": 57.6,
              "heatindex_c": 14.2,
              "heatindex_f": 57.6,
              "dewpoint_c": 4.5,
              "dewpoint_f": 40.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.4,
              "gust_kph": 5.4,
              "uv": 1
            },
            {
              "time_epoch": 1643661000,
              "time": "2022-02-01 02:00",
              "temp_c": 13.9,
              "temp_f": 57,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.8,
              "wind_kph": 2.9,
              "wind_degree": 18,
              "wind_dir": "NNE",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 54,
              "cloud": 2,
              "feelslike_c": 13.9,
              "feelslike_f": 57,
              "windchill_c": 13.9,
              "windchill_f": 57,
              "heatindex_c": 13.9,
              "heatindex_f": 57,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.8,
              "gust_kph": 6.1,
              "uv": 1
            },
            {
              "time_epoch": 1643664600,
              "time": "2022-02-01 03:00",
              "temp_c": 13.6,
              "temp_f": 56.5,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.8,
              "wind_kph": 2.9,
              "wind_degree": 346,
              "wind_dir": "NNW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 56,
              "cloud": 0,
              "feelslike_c": 13.6,
              "feelslike_f": 56.5,
              "windchill_c": 13.6,
              "windchill_f": 56.5,
              "heatindex_c": 13.6,
              "heatindex_f": 56.5,
              "dewpoint_c": 4.9,
              "dewpoint_f": 40.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.8,
              "gust_kph": 6.1,
              "uv": 1
            },
            {
              "time_epoch": 1643668200,
              "time": "2022-02-01 04:00",
              "temp_c": 13.3,
              "temp_f": 55.9,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.8,
              "wind_kph": 2.9,
              "wind_degree": 294,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 57,
              "cloud": 0,
              "feelslike_c": 13.3,
              "feelslike_f": 55.9,
              "windchill_c": 13.3,
              "windchill_f": 55.9,
              "heatindex_c": 13.3,
              "heatindex_f": 55.9,
              "dewpoint_c": 4.9,
              "dewpoint_f": 40.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.8,
              "gust_kph": 6.1,
              "uv": 1
            },
            {
              "time_epoch": 1643671800,
              "time": "2022-02-01 05:00",
              "temp_c": 13,
              "temp_f": 55.4,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 297,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 57,
              "cloud": 0,
              "feelslike_c": 13.4,
              "feelslike_f": 56.1,
              "windchill_c": 13.4,
              "windchill_f": 56.1,
              "heatindex_c": 13,
              "heatindex_f": 55.4,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.1,
              "gust_kph": 8.3,
              "uv": 1
            },
            {
              "time_epoch": 1643675400,
              "time": "2022-02-01 06:00",
              "temp_c": 12.7,
              "temp_f": 54.9,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 287,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 58,
              "cloud": 0,
              "feelslike_c": 12.8,
              "feelslike_f": 55,
              "windchill_c": 12.8,
              "windchill_f": 55,
              "heatindex_c": 12.7,
              "heatindex_f": 54.9,
              "dewpoint_c": 4.7,
              "dewpoint_f": 40.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.5,
              "gust_kph": 10.4,
              "uv": 1
            },
            {
              "time_epoch": 1643679000,
              "time": "2022-02-01 07:00",
              "temp_c": 12.6,
              "temp_f": 54.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 282,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 58,
              "cloud": 0,
              "feelslike_c": 12.4,
              "feelslike_f": 54.3,
              "windchill_c": 12.4,
              "windchill_f": 54.3,
              "heatindex_c": 12.6,
              "heatindex_f": 54.7,
              "dewpoint_c": 4.6,
              "dewpoint_f": 40.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.1,
              "gust_kph": 13,
              "uv": 4
            },
            {
              "time_epoch": 1643682600,
              "time": "2022-02-01 08:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 274,
              "wind_dir": "W",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 54,
              "cloud": 0,
              "feelslike_c": 14.1,
              "feelslike_f": 57.4,
              "windchill_c": 14.1,
              "windchill_f": 57.4,
              "heatindex_c": 14,
              "heatindex_f": 57.2,
              "dewpoint_c": 4.9,
              "dewpoint_f": 40.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.7,
              "gust_kph": 10.8,
              "uv": 4
            },
            {
              "time_epoch": 1643686200,
              "time": "2022-02-01 09:00",
              "temp_c": 16.4,
              "temp_f": 61.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 282,
              "wind_dir": "WNW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 46,
              "cloud": 0,
              "feelslike_c": 16.4,
              "feelslike_f": 61.5,
              "windchill_c": 16.4,
              "windchill_f": 61.5,
              "heatindex_c": 16.4,
              "heatindex_f": 61.5,
              "dewpoint_c": 4.6,
              "dewpoint_f": 40.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.8,
              "gust_kph": 9.4,
              "uv": 5
            },
            {
              "time_epoch": 1643689800,
              "time": "2022-02-01 10:00",
              "temp_c": 18.6,
              "temp_f": 65.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.3,
              "wind_kph": 10.1,
              "wind_degree": 287,
              "wind_dir": "WNW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 39,
              "cloud": 0,
              "feelslike_c": 18.6,
              "feelslike_f": 65.5,
              "windchill_c": 18.6,
              "windchill_f": 65.5,
              "heatindex_c": 18.6,
              "heatindex_f": 65.5,
              "dewpoint_c": 4.3,
              "dewpoint_f": 39.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.2,
              "gust_kph": 11.5,
              "uv": 5
            },
            {
              "time_epoch": 1643693400,
              "time": "2022-02-01 11:00",
              "temp_c": 22.9,
              "temp_f": 73.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 294,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 34,
              "cloud": 0,
              "feelslike_c": 23.9,
              "feelslike_f": 75,
              "windchill_c": 22.9,
              "windchill_f": 73.2,
              "heatindex_c": 23.9,
              "heatindex_f": 75,
              "dewpoint_c": 6.1,
              "dewpoint_f": 43,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.4,
              "gust_kph": 11.9,
              "uv": 6
            },
            {
              "time_epoch": 1643697000,
              "time": "2022-02-01 12:00",
              "temp_c": 24.4,
              "temp_f": 75.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 7.4,
              "wind_kph": 11.9,
              "wind_degree": 293,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 30,
              "cloud": 0,
              "feelslike_c": 24.4,
              "feelslike_f": 75.9,
              "windchill_c": 24.4,
              "windchill_f": 75.9,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 5.7,
              "dewpoint_f": 42.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.5,
              "gust_kph": 13.7,
              "uv": 6
            },
            {
              "time_epoch": 1643700600,
              "time": "2022-02-01 13:00",
              "temp_c": 25.1,
              "temp_f": 77.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 291,
              "wind_dir": "WNW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 28,
              "cloud": 0,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 25.1,
              "windchill_f": 77.2,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 5.6,
              "dewpoint_f": 42.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 7
            },
            {
              "time_epoch": 1643704200,
              "time": "2022-02-01 14:00",
              "temp_c": 25.1,
              "temp_f": 77.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 298,
              "wind_dir": "WNW",
              "pressure_mb": 1009,
              "pressure_in": 29.79,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 28,
              "cloud": 0,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 25.1,
              "windchill_f": 77.2,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 5.5,
              "dewpoint_f": 41.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.6,
              "gust_kph": 18.7,
              "uv": 7
            },
            {
              "time_epoch": 1643707800,
              "time": "2022-02-01 15:00",
              "temp_c": 24.8,
              "temp_f": 76.6,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 302,
              "wind_dir": "WNW",
              "pressure_mb": 1009,
              "pressure_in": 29.79,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 29,
              "cloud": 0,
              "feelslike_c": 24.5,
              "feelslike_f": 76.1,
              "windchill_c": 24.8,
              "windchill_f": 76.6,
              "heatindex_c": 24.5,
              "heatindex_f": 76.1,
              "dewpoint_c": 5.7,
              "dewpoint_f": 42.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.3,
              "gust_kph": 19.8,
              "uv": 6
            },
            {
              "time_epoch": 1643711400,
              "time": "2022-02-01 16:00",
              "temp_c": 24.8,
              "temp_f": 76.6,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 304,
              "wind_dir": "NW",
              "pressure_mb": 1009,
              "pressure_in": 29.78,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 33,
              "cloud": 0,
              "feelslike_c": 24.8,
              "feelslike_f": 76.6,
              "windchill_c": 24.8,
              "windchill_f": 76.6,
              "heatindex_c": 24.8,
              "heatindex_f": 76.6,
              "dewpoint_c": 7.2,
              "dewpoint_f": 45,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.7,
              "gust_kph": 17.3,
              "uv": 6
            },
            {
              "time_epoch": 1643715000,
              "time": "2022-02-01 17:00",
              "temp_c": 23.1,
              "temp_f": 73.6,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 313,
              "wind_dir": "NW",
              "pressure_mb": 1009,
              "pressure_in": 29.78,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 38,
              "cloud": 0,
              "feelslike_c": 24.3,
              "feelslike_f": 75.7,
              "windchill_c": 23.1,
              "windchill_f": 73.6,
              "heatindex_c": 24.3,
              "heatindex_f": 75.7,
              "dewpoint_c": 8.2,
              "dewpoint_f": 46.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.3,
              "gust_kph": 13.3,
              "uv": 6
            },
            {
              "time_epoch": 1643718600,
              "time": "2022-02-01 18:00",
              "temp_c": 21.3,
              "temp_f": 70.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.3,
              "wind_kph": 10.1,
              "wind_degree": 323,
              "wind_dir": "NW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 43,
              "cloud": 0,
              "feelslike_c": 21.3,
              "feelslike_f": 70.3,
              "windchill_c": 21.3,
              "windchill_f": 70.3,
              "heatindex_c": 24,
              "heatindex_f": 75.2,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.2,
              "gust_kph": 11.5,
              "uv": 1
            },
            {
              "time_epoch": 1643722200,
              "time": "2022-02-01 19:00",
              "temp_c": 20.3,
              "temp_f": 68.5,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 321,
              "wind_dir": "NW",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 46,
              "cloud": 0,
              "feelslike_c": 20.3,
              "feelslike_f": 68.5,
              "windchill_c": 20.3,
              "windchill_f": 68.5,
              "heatindex_c": 20.3,
              "heatindex_f": 68.5,
              "dewpoint_c": 8.4,
              "dewpoint_f": 47.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.9,
              "gust_kph": 11.2,
              "uv": 1
            },
            {
              "time_epoch": 1643725800,
              "time": "2022-02-01 20:00",
              "temp_c": 16.7,
              "temp_f": 62.1,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 324,
              "wind_dir": "NW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 49,
              "cloud": 0,
              "feelslike_c": 16.7,
              "feelslike_f": 62.1,
              "windchill_c": 16.7,
              "windchill_f": 62.1,
              "heatindex_c": 16.7,
              "heatindex_f": 62.1,
              "dewpoint_c": 5.9,
              "dewpoint_f": 42.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11,
              "gust_kph": 17.6,
              "uv": 1
            },
            {
              "time_epoch": 1643729400,
              "time": "2022-02-01 21:00",
              "temp_c": 16,
              "temp_f": 60.8,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 317,
              "wind_dir": "NW",
              "pressure_mb": 1012,
              "pressure_in": 29.87,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 50,
              "cloud": 0,
              "feelslike_c": 16,
              "feelslike_f": 60.8,
              "windchill_c": 16,
              "windchill_f": 60.8,
              "heatindex_c": 16,
              "heatindex_f": 60.8,
              "dewpoint_c": 5.7,
              "dewpoint_f": 42.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.6,
              "gust_kph": 15.5,
              "uv": 1
            },
            {
              "time_epoch": 1643733000,
              "time": "2022-02-01 22:00",
              "temp_c": 15.4,
              "temp_f": 59.7,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 307,
              "wind_dir": "NW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 51,
              "cloud": 0,
              "feelslike_c": 15.4,
              "feelslike_f": 59.7,
              "windchill_c": 15.4,
              "windchill_f": 59.7,
              "heatindex_c": 15.4,
              "heatindex_f": 59.7,
              "dewpoint_c": 5.4,
              "dewpoint_f": 41.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.1,
              "gust_kph": 16.2,
              "uv": 1
            },
            {
              "time_epoch": 1643736600,
              "time": "2022-02-01 23:00",
              "temp_c": 14.8,
              "temp_f": 58.6,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 301,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 52,
              "cloud": 0,
              "feelslike_c": 14.4,
              "feelslike_f": 57.9,
              "windchill_c": 14.4,
              "windchill_f": 57.9,
              "heatindex_c": 14.8,
              "heatindex_f": 58.6,
              "dewpoint_c": 5.2,
              "dewpoint_f": 41.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.2,
              "gust_kph": 18,
              "uv": 1
            }
          ]
        },
        {
          "date": "2022-02-02",
          "date_epoch": 1643760000,
          "day": {
            "maxtemp_c": 25.5,
            "maxtemp_f": 77.9,
            "mintemp_c": 11.3,
            "mintemp_f": 52.3,
            "avgtemp_c": 17.4,
            "avgtemp_f": 63.3,
            "maxwind_mph": 9.2,
            "maxwind_kph": 14.8,
            "totalprecip_mm": 0,
            "totalprecip_in": 0,
            "avgvis_km": 10,
            "avgvis_miles": 6,
            "avghumidity": 45,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 0,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "uv": 5
          },
          "astro": {
            "sunrise": "07:09 AM",
            "sunset": "06:02 PM",
            "moonrise": "08:10 AM",
            "moonset": "07:17 PM",
            "moon_phase": "Waxing Crescent",
            "moon_illumination": "2"
          },
          "hour": [
            {
              "time_epoch": 1643740200,
              "time": "2022-02-02 00:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.6,
              "wind_kph": 9,
              "wind_degree": 297,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.87,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 54,
              "cloud": 0,
              "feelslike_c": 13.6,
              "feelslike_f": 56.5,
              "windchill_c": 13.6,
              "windchill_f": 56.5,
              "heatindex_c": 14,
              "heatindex_f": 57.2,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11,
              "gust_kph": 17.6,
              "uv": 1
            },
            {
              "time_epoch": 1643743800,
              "time": "2022-02-02 01:00",
              "temp_c": 13.5,
              "temp_f": 56.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 297,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.87,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 56,
              "cloud": 0,
              "feelslike_c": 13,
              "feelslike_f": 55.4,
              "windchill_c": 13,
              "windchill_f": 55.4,
              "heatindex_c": 13.5,
              "heatindex_f": 56.3,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 1
            },
            {
              "time_epoch": 1643747400,
              "time": "2022-02-02 02:00",
              "temp_c": 13,
              "temp_f": 55.4,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 302,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 58,
              "cloud": 0,
              "feelslike_c": 12.4,
              "feelslike_f": 54.3,
              "windchill_c": 12.4,
              "windchill_f": 54.3,
              "heatindex_c": 13,
              "heatindex_f": 55.4,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 1
            },
            {
              "time_epoch": 1643751000,
              "time": "2022-02-02 03:00",
              "temp_c": 12.5,
              "temp_f": 54.5,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 300,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 59,
              "cloud": 0,
              "feelslike_c": 11.8,
              "feelslike_f": 53.2,
              "windchill_c": 11.8,
              "windchill_f": 53.2,
              "heatindex_c": 12.5,
              "heatindex_f": 54.5,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 1
            },
            {
              "time_epoch": 1643754600,
              "time": "2022-02-02 04:00",
              "temp_c": 12.1,
              "temp_f": 53.8,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 296,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 61,
              "cloud": 0,
              "feelslike_c": 11.4,
              "feelslike_f": 52.5,
              "windchill_c": 11.4,
              "windchill_f": 52.5,
              "heatindex_c": 12.1,
              "heatindex_f": 53.8,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.1,
              "gust_kph": 16.2,
              "uv": 1
            },
            {
              "time_epoch": 1643758200,
              "time": "2022-02-02 05:00",
              "temp_c": 11.7,
              "temp_f": 53.1,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 294,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 62,
              "cloud": 0,
              "feelslike_c": 11.1,
              "feelslike_f": 52,
              "windchill_c": 11.1,
              "windchill_f": 52,
              "heatindex_c": 11.7,
              "heatindex_f": 53.1,
              "dewpoint_c": 4.7,
              "dewpoint_f": 40.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 1
            },
            {
              "time_epoch": 1643761800,
              "time": "2022-02-02 06:00",
              "temp_c": 11.4,
              "temp_f": 52.5,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 286,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 62,
              "cloud": 1,
              "feelslike_c": 10.7,
              "feelslike_f": 51.3,
              "windchill_c": 10.7,
              "windchill_f": 51.3,
              "heatindex_c": 11.4,
              "heatindex_f": 52.5,
              "dewpoint_c": 4.4,
              "dewpoint_f": 39.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 1
            },
            {
              "time_epoch": 1643765400,
              "time": "2022-02-02 07:00",
              "temp_c": 11.3,
              "temp_f": 52.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 282,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 62,
              "cloud": 0,
              "feelslike_c": 10.7,
              "feelslike_f": 51.3,
              "windchill_c": 10.7,
              "windchill_f": 51.3,
              "heatindex_c": 11.3,
              "heatindex_f": 52.3,
              "dewpoint_c": 4.3,
              "dewpoint_f": 39.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.7,
              "gust_kph": 14,
              "uv": 4
            },
            {
              "time_epoch": 1643769000,
              "time": "2022-02-02 08:00",
              "temp_c": 12.7,
              "temp_f": 54.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 293,
              "wind_dir": "WNW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 57,
              "cloud": 0,
              "feelslike_c": 12.3,
              "feelslike_f": 54.1,
              "windchill_c": 12.3,
              "windchill_f": 54.1,
              "heatindex_c": 12.7,
              "heatindex_f": 54.9,
              "dewpoint_c": 4.4,
              "dewpoint_f": 39.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.2,
              "gust_kph": 11.5,
              "uv": 4
            },
            {
              "time_epoch": 1643772600,
              "time": "2022-02-02 09:00",
              "temp_c": 15.1,
              "temp_f": 59.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 300,
              "wind_dir": "WNW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 48,
              "cloud": 0,
              "feelslike_c": 15.1,
              "feelslike_f": 59.2,
              "windchill_c": 15.1,
              "windchill_f": 59.2,
              "heatindex_c": 15.1,
              "heatindex_f": 59.2,
              "dewpoint_c": 4.1,
              "dewpoint_f": 39.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.4,
              "gust_kph": 8.6,
              "uv": 5
            },
            {
              "time_epoch": 1643776200,
              "time": "2022-02-02 10:00",
              "temp_c": 17.4,
              "temp_f": 63.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 305,
              "wind_dir": "NW",
              "pressure_mb": 1013,
              "pressure_in": 29.93,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 40,
              "cloud": 2,
              "feelslike_c": 17.4,
              "feelslike_f": 63.3,
              "windchill_c": 17.4,
              "windchill_f": 63.3,
              "heatindex_c": 17.4,
              "heatindex_f": 63.3,
              "dewpoint_c": 3.7,
              "dewpoint_f": 38.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.5,
              "gust_kph": 7.2,
              "uv": 5
            },
            {
              "time_epoch": 1643779800,
              "time": "2022-02-02 11:00",
              "temp_c": 20.8,
              "temp_f": 69.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 294,
              "wind_dir": "WNW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 34,
              "cloud": 5,
              "feelslike_c": 20.8,
              "feelslike_f": 69.4,
              "windchill_c": 20.8,
              "windchill_f": 69.4,
              "heatindex_c": 20.8,
              "heatindex_f": 69.4,
              "dewpoint_c": 4.4,
              "dewpoint_f": 39.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.8,
              "gust_kph": 6.1,
              "uv": 6
            },
            {
              "time_epoch": 1643783400,
              "time": "2022-02-02 12:00",
              "temp_c": 22.3,
              "temp_f": 72.1,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 278,
              "wind_dir": "W",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 29,
              "cloud": 7,
              "feelslike_c": 23.3,
              "feelslike_f": 73.9,
              "windchill_c": 22.3,
              "windchill_f": 72.1,
              "heatindex_c": 23.3,
              "heatindex_f": 73.9,
              "dewpoint_c": 3.5,
              "dewpoint_f": 38.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.8,
              "gust_kph": 6.1,
              "uv": 6
            },
            {
              "time_epoch": 1643787000,
              "time": "2022-02-02 13:00",
              "temp_c": 23.9,
              "temp_f": 75,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 262,
              "wind_dir": "W",
              "pressure_mb": 1011,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 26,
              "cloud": 5,
              "feelslike_c": 23.7,
              "feelslike_f": 74.7,
              "windchill_c": 23.9,
              "windchill_f": 75,
              "heatindex_c": 23.7,
              "heatindex_f": 74.7,
              "dewpoint_c": 3.2,
              "dewpoint_f": 37.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.8,
              "gust_kph": 6.1,
              "uv": 6
            },
            {
              "time_epoch": 1643790600,
              "time": "2022-02-02 14:00",
              "temp_c": 25,
              "temp_f": 77,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 256,
              "wind_dir": "WSW",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 24,
              "cloud": 4,
              "feelslike_c": 24.2,
              "feelslike_f": 75.6,
              "windchill_c": 25,
              "windchill_f": 77,
              "heatindex_c": 24.2,
              "heatindex_f": 75.6,
              "dewpoint_c": 3.2,
              "dewpoint_f": 37.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.1,
              "gust_kph": 5,
              "uv": 7
            },
            {
              "time_epoch": 1643794200,
              "time": "2022-02-02 15:00",
              "temp_c": 25.5,
              "temp_f": 77.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 241,
              "wind_dir": "WSW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 24,
              "cloud": 2,
              "feelslike_c": 24.5,
              "feelslike_f": 76.1,
              "windchill_c": 25.5,
              "windchill_f": 77.9,
              "heatindex_c": 24.5,
              "heatindex_f": 76.1,
              "dewpoint_c": 3.6,
              "dewpoint_f": 38.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.2,
              "gust_kph": 3.6,
              "uv": 7
            },
            {
              "time_epoch": 1643797800,
              "time": "2022-02-02 16:00",
              "temp_c": 25.1,
              "temp_f": 77.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 1.3,
              "wind_kph": 2.2,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 27,
              "cloud": 1,
              "feelslike_c": 24.5,
              "feelslike_f": 76.1,
              "windchill_c": 25.1,
              "windchill_f": 77.2,
              "heatindex_c": 24.5,
              "heatindex_f": 76.1,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 1.6,
              "gust_kph": 2.5,
              "uv": 7
            },
            {
              "time_epoch": 1643801400,
              "time": "2022-02-02 17:00",
              "temp_c": 23.1,
              "temp_f": 73.6,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 1.8,
              "wind_kph": 2.9,
              "wind_degree": 138,
              "wind_dir": "SE",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 33,
              "cloud": 0,
              "feelslike_c": 23.9,
              "feelslike_f": 75,
              "windchill_c": 23.1,
              "windchill_f": 73.6,
              "heatindex_c": 23.9,
              "heatindex_f": 75,
              "dewpoint_c": 6,
              "dewpoint_f": 42.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2,
              "gust_kph": 3.2,
              "uv": 6
            },
            {
              "time_epoch": 1643805000,
              "time": "2022-02-02 18:00",
              "temp_c": 21.4,
              "temp_f": 70.5,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4,
              "wind_kph": 6.5,
              "wind_degree": 117,
              "wind_dir": "ESE",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 37,
              "cloud": 0,
              "feelslike_c": 21.4,
              "feelslike_f": 70.5,
              "windchill_c": 21.4,
              "windchill_f": 70.5,
              "heatindex_c": 23.7,
              "heatindex_f": 74.7,
              "dewpoint_c": 6.1,
              "dewpoint_f": 43,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.7,
              "gust_kph": 7.6,
              "uv": 1
            },
            {
              "time_epoch": 1643808600,
              "time": "2022-02-02 19:00",
              "temp_c": 20.4,
              "temp_f": 68.7,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 106,
              "wind_dir": "ESE",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 41,
              "cloud": 0,
              "feelslike_c": 20.4,
              "feelslike_f": 68.7,
              "windchill_c": 20.4,
              "windchill_f": 68.7,
              "heatindex_c": 20.4,
              "heatindex_f": 68.7,
              "dewpoint_c": 6.5,
              "dewpoint_f": 43.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.9,
              "gust_kph": 11.2,
              "uv": 1
            },
            {
              "time_epoch": 1643812200,
              "time": "2022-02-02 20:00",
              "temp_c": 16.8,
              "temp_f": 62.2,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 109,
              "wind_dir": "ESE",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 44,
              "cloud": 0,
              "feelslike_c": 16.8,
              "feelslike_f": 62.2,
              "windchill_c": 16.8,
              "windchill_f": 62.2,
              "heatindex_c": 16.8,
              "heatindex_f": 62.2,
              "dewpoint_c": 4.4,
              "dewpoint_f": 39.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.8,
              "gust_kph": 20.5,
              "uv": 1
            },
            {
              "time_epoch": 1643815800,
              "time": "2022-02-02 21:00",
              "temp_c": 16.3,
              "temp_f": 61.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 8.1,
              "wind_kph": 13,
              "wind_degree": 115,
              "wind_dir": "ESE",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 46,
              "cloud": 0,
              "feelslike_c": 16.3,
              "feelslike_f": 61.3,
              "windchill_c": 16.3,
              "windchill_f": 61.3,
              "heatindex_c": 16.3,
              "heatindex_f": 61.3,
              "dewpoint_c": 4.7,
              "dewpoint_f": 40.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 1
            },
            {
              "time_epoch": 1643819400,
              "time": "2022-02-02 22:00",
              "temp_c": 15.8,
              "temp_f": 60.4,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 8.1,
              "wind_kph": 13,
              "wind_degree": 110,
              "wind_dir": "ESE",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 48,
              "cloud": 0,
              "feelslike_c": 15.8,
              "feelslike_f": 60.4,
              "windchill_c": 15.8,
              "windchill_f": 60.4,
              "heatindex_c": 15.8,
              "heatindex_f": 60.4,
              "dewpoint_c": 4.7,
              "dewpoint_f": 40.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.9,
              "gust_kph": 25.6,
              "uv": 1
            },
            {
              "time_epoch": 1643823000,
              "time": "2022-02-02 23:00",
              "temp_c": 15.7,
              "temp_f": 60.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 109,
              "wind_dir": "ESE",
              "pressure_mb": 1011,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 48,
              "cloud": 1,
              "feelslike_c": 15.7,
              "feelslike_f": 60.3,
              "windchill_c": 15.7,
              "windchill_f": 60.3,
              "heatindex_c": 15.7,
              "heatindex_f": 60.3,
              "dewpoint_c": 4.6,
              "dewpoint_f": 40.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.4,
              "gust_kph": 28.1,
              "uv": 1
            }
          ]
        },
        {
          "date": "2022-02-03",
          "date_epoch": 1643846400,
          "day": {
            "maxtemp_c": 19,
            "maxtemp_f": 66.2,
            "mintemp_c": 13.3,
            "mintemp_f": 55.9,
            "avgtemp_c": 15.5,
            "avgtemp_f": 60,
            "maxwind_mph": 18.1,
            "maxwind_kph": 29.2,
            "totalprecip_mm": 20.4,
            "totalprecip_in": 0.8,
            "avgvis_km": 9.5,
            "avgvis_miles": 5,
            "avghumidity": 66,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 89,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Heavy rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/308.png",
              "code": 1195
            },
            "uv": 4
          },
          "astro": {
            "sunrise": "07:09 AM",
            "sunset": "06:02 PM",
            "moonrise": "08:49 AM",
            "moonset": "08:21 PM",
            "moon_phase": "Waxing Crescent",
            "moon_illumination": "10"
          },
          "hour": [
            {
              "time_epoch": 1643826600,
              "time": "2022-02-03 00:00",
              "temp_c": 15.7,
              "temp_f": 60.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 105,
              "wind_dir": "ESE",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 46,
              "cloud": 3,
              "feelslike_c": 15.7,
              "feelslike_f": 60.3,
              "windchill_c": 15.7,
              "windchill_f": 60.3,
              "heatindex_c": 15.7,
              "heatindex_f": 60.3,
              "dewpoint_c": 4.2,
              "dewpoint_f": 39.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.9,
              "gust_kph": 28.8,
              "uv": 1
            },
            {
              "time_epoch": 1643830200,
              "time": "2022-02-03 01:00",
              "temp_c": 15.8,
              "temp_f": 60.4,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 111,
              "wind_dir": "ESE",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 45,
              "cloud": 7,
              "feelslike_c": 15.8,
              "feelslike_f": 60.4,
              "windchill_c": 15.8,
              "windchill_f": 60.4,
              "heatindex_c": 15.8,
              "heatindex_f": 60.4,
              "dewpoint_c": 3.9,
              "dewpoint_f": 39,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19,
              "gust_kph": 30.6,
              "uv": 1
            },
            {
              "time_epoch": 1643833800,
              "time": "2022-02-03 02:00",
              "temp_c": 15.6,
              "temp_f": 60.1,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 109,
              "wind_dir": "ESE",
              "pressure_mb": 1008,
              "pressure_in": 29.77,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 45,
              "cloud": 19,
              "feelslike_c": 15.6,
              "feelslike_f": 60.1,
              "windchill_c": 15.6,
              "windchill_f": 60.1,
              "heatindex_c": 15.6,
              "heatindex_f": 60.1,
              "dewpoint_c": 3.9,
              "dewpoint_f": 39,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.5,
              "gust_kph": 31.3,
              "uv": 1
            },
            {
              "time_epoch": 1643837400,
              "time": "2022-02-03 03:00",
              "temp_c": 15.4,
              "temp_f": 59.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 13.6,
              "wind_kph": 22,
              "wind_degree": 114,
              "wind_dir": "ESE",
              "pressure_mb": 1008,
              "pressure_in": 29.76,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 47,
              "cloud": 32,
              "feelslike_c": 15.4,
              "feelslike_f": 59.7,
              "windchill_c": 15.4,
              "windchill_f": 59.7,
              "heatindex_c": 15.4,
              "heatindex_f": 59.7,
              "dewpoint_c": 4,
              "dewpoint_f": 39.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 20.1,
              "gust_kph": 32.4,
              "uv": 1
            },
            {
              "time_epoch": 1643841000,
              "time": "2022-02-03 04:00",
              "temp_c": 15.1,
              "temp_f": 59.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 14.3,
              "wind_kph": 23,
              "wind_degree": 120,
              "wind_dir": "ESE",
              "pressure_mb": 1007,
              "pressure_in": 29.73,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 48,
              "cloud": 46,
              "feelslike_c": 15.1,
              "feelslike_f": 59.2,
              "windchill_c": 15.1,
              "windchill_f": 59.2,
              "heatindex_c": 15.1,
              "heatindex_f": 59.2,
              "dewpoint_c": 4.3,
              "dewpoint_f": 39.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 21.9,
              "gust_kph": 35.3,
              "uv": 1
            },
            {
              "time_epoch": 1643844600,
              "time": "2022-02-03 05:00",
              "temp_c": 15.1,
              "temp_f": 59.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 13.2,
              "wind_kph": 21.2,
              "wind_degree": 115,
              "wind_dir": "ESE",
              "pressure_mb": 1007,
              "pressure_in": 29.74,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 50,
              "cloud": 44,
              "feelslike_c": 15.1,
              "feelslike_f": 59.2,
              "windchill_c": 15.1,
              "windchill_f": 59.2,
              "heatindex_c": 15.1,
              "heatindex_f": 59.2,
              "dewpoint_c": 4.7,
              "dewpoint_f": 40.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19,
              "gust_kph": 30.6,
              "uv": 1
            },
            {
              "time_epoch": 1643848200,
              "time": "2022-02-03 06:00",
              "temp_c": 14.7,
              "temp_f": 58.5,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 14.1,
              "wind_kph": 22.7,
              "wind_degree": 118,
              "wind_dir": "ESE",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 52,
              "cloud": 50,
              "feelslike_c": 13.1,
              "feelslike_f": 55.6,
              "windchill_c": 13.1,
              "windchill_f": 55.6,
              "heatindex_c": 14.7,
              "heatindex_f": 58.5,
              "dewpoint_c": 4.9,
              "dewpoint_f": 40.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.9,
              "gust_kph": 32,
              "uv": 1
            },
            {
              "time_epoch": 1643851800,
              "time": "2022-02-03 07:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 15.2,
              "wind_kph": 24.5,
              "wind_degree": 117,
              "wind_dir": "ESE",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 58,
              "cloud": 40,
              "feelslike_c": 12.1,
              "feelslike_f": 53.8,
              "windchill_c": 12.1,
              "windchill_f": 53.8,
              "heatindex_c": 14,
              "heatindex_f": 57.2,
              "dewpoint_c": 5.8,
              "dewpoint_f": 42.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 21.7,
              "gust_kph": 34.9,
              "uv": 4
            },
            {
              "time_epoch": 1643855400,
              "time": "2022-02-03 08:00",
              "temp_c": 13.8,
              "temp_f": 56.8,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 14.5,
              "wind_kph": 23.4,
              "wind_degree": 127,
              "wind_dir": "SE",
              "pressure_mb": 1008,
              "pressure_in": 29.77,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 62,
              "cloud": 88,
              "feelslike_c": 11.9,
              "feelslike_f": 53.4,
              "windchill_c": 11.9,
              "windchill_f": 53.4,
              "heatindex_c": 13.8,
              "heatindex_f": 56.8,
              "dewpoint_c": 6.6,
              "dewpoint_f": 43.9,
              "will_it_rain": 1,
              "chance_of_rain": 75,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 20.8,
              "gust_kph": 33.5,
              "uv": 3
            },
            {
              "time_epoch": 1643859000,
              "time": "2022-02-03 09:00",
              "temp_c": 15.1,
              "temp_f": 59.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 15.9,
              "wind_kph": 25.6,
              "wind_degree": 127,
              "wind_dir": "SE",
              "pressure_mb": 1008,
              "pressure_in": 29.78,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 61,
              "cloud": 81,
              "feelslike_c": 15.1,
              "feelslike_f": 59.2,
              "windchill_c": 15.1,
              "windchill_f": 59.2,
              "heatindex_c": 15.1,
              "heatindex_f": 59.2,
              "dewpoint_c": 7.7,
              "dewpoint_f": 45.9,
              "will_it_rain": 0,
              "chance_of_rain": 62,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.9,
              "gust_kph": 32,
              "uv": 4
            },
            {
              "time_epoch": 1643862600,
              "time": "2022-02-03 10:00",
              "temp_c": 15.8,
              "temp_f": 60.4,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 18.1,
              "wind_kph": 29.2,
              "wind_degree": 117,
              "wind_dir": "ESE",
              "pressure_mb": 1008,
              "pressure_in": 29.77,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 60,
              "cloud": 73,
              "feelslike_c": 15.8,
              "feelslike_f": 60.4,
              "windchill_c": 15.8,
              "windchill_f": 60.4,
              "heatindex_c": 15.8,
              "heatindex_f": 60.4,
              "dewpoint_c": 8.2,
              "dewpoint_f": 46.8,
              "will_it_rain": 1,
              "chance_of_rain": 78,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 22.8,
              "gust_kph": 36.7,
              "uv": 4
            },
            {
              "time_epoch": 1643866200,
              "time": "2022-02-03 11:00",
              "temp_c": 17.8,
              "temp_f": 64,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 17.2,
              "wind_kph": 27.7,
              "wind_degree": 115,
              "wind_dir": "ESE",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 1,
              "precip_in": 0.04,
              "humidity": 61,
              "cloud": 70,
              "feelslike_c": 17.8,
              "feelslike_f": 64,
              "windchill_c": 17.8,
              "windchill_f": 64,
              "heatindex_c": 17.8,
              "heatindex_f": 64,
              "dewpoint_c": 10.2,
              "dewpoint_f": 50.4,
              "will_it_rain": 1,
              "chance_of_rain": 79,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 22.6,
              "gust_kph": 36.4,
              "uv": 4
            },
            {
              "time_epoch": 1643869800,
              "time": "2022-02-03 12:00",
              "temp_c": 18,
              "temp_f": 64.4,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 16.8,
              "wind_kph": 27,
              "wind_degree": 115,
              "wind_dir": "ESE",
              "pressure_mb": 1007,
              "pressure_in": 29.73,
              "precip_mm": 0.4,
              "precip_in": 0.02,
              "humidity": 61,
              "cloud": 73,
              "feelslike_c": 18,
              "feelslike_f": 64.4,
              "windchill_c": 18,
              "windchill_f": 64.4,
              "heatindex_c": 18,
              "heatindex_f": 64.4,
              "dewpoint_c": 10.4,
              "dewpoint_f": 50.7,
              "will_it_rain": 1,
              "chance_of_rain": 79,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 20.1,
              "gust_kph": 32.4,
              "uv": 4
            },
            {
              "time_epoch": 1643873400,
              "time": "2022-02-03 13:00",
              "temp_c": 19,
              "temp_f": 66.2,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 16.3,
              "wind_kph": 26.3,
              "wind_degree": 118,
              "wind_dir": "ESE",
              "pressure_mb": 1005,
              "pressure_in": 29.69,
              "precip_mm": 0.4,
              "precip_in": 0.02,
              "humidity": 58,
              "cloud": 100,
              "feelslike_c": 19,
              "feelslike_f": 66.2,
              "windchill_c": 19,
              "windchill_f": 66.2,
              "heatindex_c": 19,
              "heatindex_f": 66.2,
              "dewpoint_c": 10.6,
              "dewpoint_f": 51.1,
              "will_it_rain": 1,
              "chance_of_rain": 79,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 20.8,
              "gust_kph": 33.5,
              "uv": 4
            },
            {
              "time_epoch": 1643877000,
              "time": "2022-02-03 14:00",
              "temp_c": 18,
              "temp_f": 64.4,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 13.4,
              "wind_kph": 21.6,
              "wind_degree": 111,
              "wind_dir": "ESE",
              "pressure_mb": 1004,
              "pressure_in": 29.66,
              "precip_mm": 1,
              "precip_in": 0.04,
              "humidity": 62,
              "cloud": 72,
              "feelslike_c": 18,
              "feelslike_f": 64.4,
              "windchill_c": 18,
              "windchill_f": 64.4,
              "heatindex_c": 18,
              "heatindex_f": 64.4,
              "dewpoint_c": 10.6,
              "dewpoint_f": 51.1,
              "will_it_rain": 0,
              "chance_of_rain": 68,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.4,
              "gust_kph": 28.1,
              "uv": 4
            },
            {
              "time_epoch": 1643880600,
              "time": "2022-02-03 15:00",
              "temp_c": 17.8,
              "temp_f": 64,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 13.4,
              "wind_kph": 21.6,
              "wind_degree": 103,
              "wind_dir": "ESE",
              "pressure_mb": 1004,
              "pressure_in": 29.64,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 65,
              "cloud": 86,
              "feelslike_c": 17.8,
              "feelslike_f": 64,
              "windchill_c": 17.8,
              "windchill_f": 64,
              "heatindex_c": 17.8,
              "heatindex_f": 64,
              "dewpoint_c": 11.2,
              "dewpoint_f": 52.2,
              "will_it_rain": 0,
              "chance_of_rain": 69,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.3,
              "gust_kph": 29.5,
              "uv": 4
            },
            {
              "time_epoch": 1643884200,
              "time": "2022-02-03 16:00",
              "temp_c": 18,
              "temp_f": 64.4,
              "is_day": 1,
              "condition": {
                "text": "Patchy light rain with thunder",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/386.png",
                "code": 1273
              },
              "wind_mph": 13.2,
              "wind_kph": 21.2,
              "wind_degree": 94,
              "wind_dir": "E",
              "pressure_mb": 1003,
              "pressure_in": 29.61,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 67,
              "cloud": 86,
              "feelslike_c": 18,
              "feelslike_f": 64.4,
              "windchill_c": 18,
              "windchill_f": 64.4,
              "heatindex_c": 18,
              "heatindex_f": 64.4,
              "dewpoint_c": 11.8,
              "dewpoint_f": 53.2,
              "will_it_rain": 1,
              "chance_of_rain": 71,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.6,
              "gust_kph": 29.9,
              "uv": 4
            },
            {
              "time_epoch": 1643887800,
              "time": "2022-02-03 17:00",
              "temp_c": 16.2,
              "temp_f": 61.2,
              "is_day": 1,
              "condition": {
                "text": "Moderate or heavy rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/356.png",
                "code": 1243
              },
              "wind_mph": 12.1,
              "wind_kph": 19.4,
              "wind_degree": 82,
              "wind_dir": "E",
              "pressure_mb": 1003,
              "pressure_in": 29.6,
              "precip_mm": 2.5,
              "precip_in": 0.1,
              "humidity": 80,
              "cloud": 83,
              "feelslike_c": 16.2,
              "feelslike_f": 61.2,
              "windchill_c": 16.2,
              "windchill_f": 61.2,
              "heatindex_c": 16.2,
              "heatindex_f": 61.2,
              "dewpoint_c": 12.7,
              "dewpoint_f": 54.9,
              "will_it_rain": 1,
              "chance_of_rain": 80,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 18.6,
              "gust_kph": 29.9,
              "uv": 4
            },
            {
              "time_epoch": 1643891400,
              "time": "2022-02-03 18:00",
              "temp_c": 14.5,
              "temp_f": 58.1,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 81,
              "wind_dir": "E",
              "pressure_mb": 1003,
              "pressure_in": 29.63,
              "precip_mm": 1.2,
              "precip_in": 0.05,
              "humidity": 89,
              "cloud": 74,
              "feelslike_c": 13,
              "feelslike_f": 55.4,
              "windchill_c": 13,
              "windchill_f": 55.4,
              "heatindex_c": 14.5,
              "heatindex_f": 58.1,
              "dewpoint_c": 12.7,
              "dewpoint_f": 54.9,
              "will_it_rain": 1,
              "chance_of_rain": 83,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 18.3,
              "gust_kph": 29.5,
              "uv": 1
            },
            {
              "time_epoch": 1643895000,
              "time": "2022-02-03 19:00",
              "temp_c": 14.1,
              "temp_f": 57.4,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 87,
              "wind_dir": "E",
              "pressure_mb": 1004,
              "pressure_in": 29.65,
              "precip_mm": 1.1,
              "precip_in": 0.04,
              "humidity": 91,
              "cloud": 84,
              "feelslike_c": 12.7,
              "feelslike_f": 54.9,
              "windchill_c": 12.7,
              "windchill_f": 54.9,
              "heatindex_c": 14.1,
              "heatindex_f": 57.4,
              "dewpoint_c": 12.6,
              "dewpoint_f": 54.7,
              "will_it_rain": 0,
              "chance_of_rain": 66,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.9,
              "gust_kph": 28.8,
              "uv": 1
            },
            {
              "time_epoch": 1643898600,
              "time": "2022-02-03 20:00",
              "temp_c": 13.5,
              "temp_f": 56.3,
              "is_day": 0,
              "condition": {
                "text": "Moderate or heavy rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/356.png",
                "code": 1243
              },
              "wind_mph": 8.5,
              "wind_kph": 13.7,
              "wind_degree": 104,
              "wind_dir": "ESE",
              "pressure_mb": 1005,
              "pressure_in": 29.67,
              "precip_mm": 3.4,
              "precip_in": 0.13,
              "humidity": 93,
              "cloud": 93,
              "feelslike_c": 12.4,
              "feelslike_f": 54.3,
              "windchill_c": 12.4,
              "windchill_f": 54.3,
              "heatindex_c": 13.5,
              "heatindex_f": 56.3,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 0,
              "chance_of_rain": 63,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 14.3,
              "gust_kph": 23,
              "uv": 1
            },
            {
              "time_epoch": 1643902200,
              "time": "2022-02-03 21:00",
              "temp_c": 13.3,
              "temp_f": 55.9,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 142,
              "wind_dir": "SE",
              "pressure_mb": 1006,
              "pressure_in": 29.7,
              "precip_mm": 1.2,
              "precip_in": 0.05,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": 12.5,
              "feelslike_f": 54.5,
              "windchill_c": 12.5,
              "windchill_f": 54.5,
              "heatindex_c": 13.3,
              "heatindex_f": 55.9,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 1,
              "chance_of_rain": 83,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.1,
              "gust_kph": 19.4,
              "uv": 1
            },
            {
              "time_epoch": 1643905800,
              "time": "2022-02-03 22:00",
              "temp_c": 13.4,
              "temp_f": 56.1,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 157,
              "wind_dir": "SSE",
              "pressure_mb": 1006,
              "pressure_in": 29.72,
              "precip_mm": 1.2,
              "precip_in": 0.05,
              "humidity": 94,
              "cloud": 78,
              "feelslike_c": 12.9,
              "feelslike_f": 55.2,
              "windchill_c": 12.9,
              "windchill_f": 55.2,
              "heatindex_c": 13.4,
              "heatindex_f": 56.1,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 1,
              "chance_of_rain": 71,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.8,
              "gust_kph": 15.8,
              "uv": 1
            },
            {
              "time_epoch": 1643909400,
              "time": "2022-02-03 23:00",
              "temp_c": 13.3,
              "temp_f": 55.9,
              "is_day": 0,
              "condition": {
                "text": "Moderate or heavy rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/356.png",
                "code": 1243
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 138,
              "wind_dir": "SE",
              "pressure_mb": 1006,
              "pressure_in": 29.7,
              "precip_mm": 5.9,
              "precip_in": 0.23,
              "humidity": 94,
              "cloud": 67,
              "feelslike_c": 13,
              "feelslike_f": 55.4,
              "windchill_c": 13,
              "windchill_f": 55.4,
              "heatindex_c": 13.3,
              "heatindex_f": 55.9,
              "dewpoint_c": 12.3,
              "dewpoint_f": 54.1,
              "will_it_rain": 1,
              "chance_of_rain": 89,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 8.9,
              "gust_kph": 14.4,
              "uv": 1
            }
          ]
        }
      ]
    }
  }
  console.log(weatherResponse);
  const [temperatureUnit, setTemperatureUnit] = useState('celsius');
  return (
    <>
      <div className="container py-4">
        <main className="Shadow-lg bg-light rounded-3 overflow-hidden">
          <div className="row">
            <div className="col-sm-4">
              <div className="bg-white p-5 d-flex flex-column">
                <div className="d-flex align-items-center">
                  <TopSearchBar value='' />
                </div>
                <img src={weatherResponse.current.condition.icon} alt="logo" className="img-fluid col-4" />
                <Heading level="2" content={`${temperatureUnit === 'celsius' ? weatherResponse.current.temp_c : weatherResponse.current.temp_f}`} styleClass='display-3 text-center fw-light d-flex align-items-center' subContent={`${temperatureUnit === 'celsius' ? '°C' : '°f'}`} />
                <Heading level="2" content={weatherResponse.location.name} styleClass='h4 text-center fw-light d-flex align-items-center'></Heading>
                <hr />
                <p>{weatherResponse.current.condition.text}</p>
                <p>{weatherResponse.forecast.forecastday[0].day.maxtemp_c} / {weatherResponse.forecast.forecastday[0].day.mintemp_c}</p>
              </div>
            </div>
            <div className="col-sm-8">
              <div className="d-flex justify-content-between py-4 pe-4">
                <h3 className='h5 fw-normal border-bottom border-dark pb-1'>Forecast</h3>
                <div className="d-flex">
                  <input type="radio" className="btn-check" name="options-outlined" id="success-outlined" autoComplete="off" checked />
                  <label className="btn btn-outline-dark rounded-pill d-flex justify-content-center p-1" htmlFor="success-outlined">°C</label>

                  <input type="radio" className="btn-check" name="options-outlined" id="danger-outlined" autoComplete="off" />
                  <label className="btn btn-outline-dark rounded-pill d-flex justify-content-center p-1 ms-2" htmlFor="danger-outlined">°F</label>
                </div>
              </div>

              {weatherResponse.forecast.forecastday.map((element, index) => {
                return (
                  <div className="row">
                    {
                      element.hour.map((item, number) => {
                        return (

                          <div className="col-sm-2" key={number}>
                            {/* {number % 2  ? ' yes' : ' ' } */}
                            <div className="bg-white p-3 shadow rounded-3 mb-2 text-center">
                              <h3 className="h6">{item.time.slice(0, 10)}</h3>
                              <h3 className="h6">{item.time.slice(10, 16)}</h3>
                              <img src={element.day.condition.icon} alt="logo" className="img-fluid" />
                              <p className="mb-0">
                                <span>{item.temp_c} / {item.temp_f}</span>
                              </p>
                            </div>
                          </div>
                        )
                      })
                    }
                  </div>
                )
              })}

              <div className="row mt-3">
                <div className="col-12">
                  <h5 className="fw-normal">Today Highlights</h5>
                </div>
                <div className="col-sm-4">
                  <div className="bg-white p-2">

                  </div>
                </div>
              </div>
            </div>
          </div>

        </main>
      </div>
    </>
  );
}
